# Generated by Django 3.2.5 on 2021-08-19 12:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0003_auto_20210819_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='egitmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Egitmen_ismi', models.CharField(max_length=50)),
                ('egitmen_bilgisi', models.CharField(max_length=255)),
                ('Egitmen_Resmi', models.ImageField(upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='urunl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('aciklama', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kontejan', models.IntegerField(default=0)),
                ('minimum_kontejan', models.IntegerField(default=3)),
                ('detay', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(unique=True)),
                ('Durum', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('egitim_tarihi', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.kategoriler')),
                ('egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.egitmen')),
            ],
        ),
        migrations.DeleteModel(
            name='urunler',
        ),
    ]
