# Generated by Django 3.2.5 on 2021-08-19 23:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0004_auto_20210819_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('aciklama1', models.TextField(max_length=100)),
                ('aciklama2', models.TextField(max_length=100)),
                ('aciklama3', models.TextField(max_length=100)),
                ('aciklama4', models.TextField(max_length=100)),
                ('aciklama5', models.TextField(max_length=100)),
                ('egitim_gunleri', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kontejan', models.IntegerField(default=0)),
                ('urun_sag_metin', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(unique=True)),
                ('Durum', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('toplam_egitim_saati', models.CharField(max_length=50)),
                ('egitim_tarihi', models.DateTimeField()),
                ('egitim_bitis_tarihi', models.DateTimeField()),
                ('urun_aciklama', ckeditor_uploader.fields.RichTextUploadingField()),
                ('urun_mufredat', ckeditor_uploader.fields.RichTextUploadingField()),
                ('urun_tarih_ucret', ckeditor_uploader.fields.RichTextUploadingField()),
                ('urun_sertifikalar', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.kategoriler')),
                ('egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.egitmen')),
            ],
        ),
        migrations.DeleteModel(
            name='urunl',
        ),
    ]
