# Generated by Django 3.2.5 on 2021-08-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0007_auto_20210820_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egitiml',
            name='urun_mufredat',
        ),
        migrations.RemoveField(
            model_name='egitiml',
            name='urun_sertifikalar',
        ),
        migrations.RemoveField(
            model_name='egitiml',
            name='urun_tarih_ucret',
        ),
    ]
