# Generated by Django 3.2.5 on 2021-08-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0009_auto_20210820_0229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urunl',
            new_name='urunler',
        ),
    ]
