# Generated by Django 3.2.5 on 2021-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0014_urunl_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='link',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
