# Generated by Django 3.2.5 on 2021-08-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0018_alter_urunl_odeme_linki'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitmen',
            name='egitmen_link1',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='egitmen',
            name='egitmen_link2',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='egitmen',
            name='egitmen_link3',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='egitmen',
            name='egitmen_link4',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
    ]
